name: Horusec Security Scan

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  horusec_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest

      - name: Run Horusec Scan
        run: |
          horusec start \
            -p . \
            --config-file-path=horusec-config.json \
            --information-severity=true \
            --disable-docker \
            --output-format json \
            --json-output-file horusec-report.json

          # Solo falla si hay CRITICAL/HIGH
          CRITICAL_COUNT=$(jq '[.analysisVulnerabilities[].vulnerabilities | select(.severity=="CRITICAL" or .severity=="HIGH")] | length' horusec-report.json)
          if [ "$CRITICAL_COUNT" -gt 2 ]; then
            echo "Found $CRITICAL_COUNT critical/high vulnerabilities!"
            exit 1
          fi
